version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
        - .env
    command: tail -f /dev/null

